apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: vidx-prod
type: Opaque
data:
  username: dmlkeA== # base64 encoded: vidx
  password: dmlkeA== # base64 encoded: vidx
  root-password: dmlkeA== # base64 encoded: vidx
