apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: vidx-prod
type: Opaque
data:
  default-user: dmlkeA== # base64 encoded: vidx
  default-pass: dmlkeA== # base64 encoded: vidx
